try {
    console.log(a);
    console.log(`ending try`);
} catch (error) {
    console.log(`error handled`);    
}finally{
    console.log(`finally`);
}
console.log(`end`);